name: intrasom_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python 
  - matplotlib=3.7.1
  - scipy=1.10.1
  - joblib=1.2.0
  - scikit-learn=1.2.2
  - pandas=2.0.1
  - tqdm=4.65.0
  - plotly=5.14.1
  - scikit-image=0.20.0
  - pyarrow=9.0.0
  - openpyxl=3.1.2
  
  - geopandas=0.13.0
  - shapely=2.0.1
  
  - jupyter
  - pip
  - ipywidgets=8.0.6
  

  - pip:
      - intrasom